name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-test:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run linter (flake8)
      run: |
        pip install flake8
        flake8 app
    - name: Run tests (pytest)
      run: |
        pip install pytest
        pytest tests/
  #deploy:
  #  name: Deploy to GCP
  #  needs: build-test
  #  runs-on: ubuntu-latest
  #  if: github.ref == 'refs/heads/master'
  #  steps:
  #  - name: Checkout code
  #    uses: actions/checkout@v3
  #  - name: Set up GCP credentials
  #    uses: google-github-actions/auth@v1
  #    with:
  #      credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  #  - name: Set up Google Cloud SDK
  #    uses: google-github-actions/setup-gcloud@v1
  #    with:
  #      project_id: ${{ secrets.GCP_PROJECT_ID }}
  #  - name: Deploy app (replace with your deploy logic)
  #    run: |
  #      echo "Run your GCP deployment command here (e.g., gcloud app deploy, GKE, Cloud Run)"
