data_loader:
  path: C:\Users\gonpr\Downloads\creditcard_2023.csv
train_test_split:
  test_size: 0.05
  train_sizes: [0.5]
optimization:
  cross_validator: 5
  scoring_metric: 'accuracy'
  model_selection:
    param_grid:
      LogisticRegression:
        tol: [0.0001, 0.00005]
        max_iter: [40]
      DecisionTreeClassifier:
        max_depth: [20]
        min_samples_leaf: [2, 5]
        max_leaf_nodes: [10]
      RandomForestClassifier:
        n_estimators: [10, 20]
        max_depth: [20]
        min_samples_leaf: [2, 5]
        max_leaf_nodes: [10]
      XGBClassifier:
        n_estimators: [10, 20]
        max_depth: [20]
  feature_selection:
    tolerance: 0.0005
